version: '3'
services:
  gateway:
    build:
      context: ..
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - svc-network

networks:
  svc-network:
    external: true